#ifndef LVGL_APP_CONFIG_H
#define LVGL_APP_CONFIG_H

#include <nuttx/config.h>

#ifndef CONFIG_LVGL_APP_APP_MAIN_PRIORITY
#  define CONFIG_LVGL_APP_APP_MAIN_PRIORITY 100
#endif

#ifndef CONFIG_LVGL_APP_APP_MAIN_STACKSIZE
#  define CONFIG_LVGL_APP_APP_MAIN_STACKSIZE 32768
#endif

#ifndef CONFIG_LVGL_APP_APP_MAIN_LOOP_MIN_SLEEP_MS
#  define CONFIG_LVGL_APP_APP_MAIN_LOOP_MIN_SLEEP_MS 1
#endif

#ifndef CONFIG_LVGL_APP_APP_MAIN_LOOP_MAX_SLEEP_MS
#  define CONFIG_LVGL_APP_APP_MAIN_LOOP_MAX_SLEEP_MS 30
#endif

#ifndef CONFIG_LVGL_APP_APP_MAIN_AUTOSTART_DELAY_MS
#  define CONFIG_LVGL_APP_APP_MAIN_AUTOSTART_DELAY_MS 1500
#endif

#ifndef CONFIG_LVGL_APP_HAL_DISPLAY_FB_PATH
#  define CONFIG_LVGL_APP_HAL_DISPLAY_FB_PATH "/dev/fb0"
#endif

#ifndef CONFIG_LVGL_APP_HAL_DISPLAY_DEVICE_WAIT_MS
#  define CONFIG_LVGL_APP_HAL_DISPLAY_DEVICE_WAIT_MS 3000
#endif

#ifndef CONFIG_LVGL_APP_HAL_INPUT_DEV_PATH
#  define CONFIG_LVGL_APP_HAL_INPUT_DEV_PATH "/dev/input0"
#endif

#ifndef CONFIG_LVGL_APP_BACKLIGHT_PWM_PATH
#  define CONFIG_LVGL_APP_BACKLIGHT_PWM_PATH "/dev/pwm2"
#endif

#ifndef CONFIG_LVGL_APP_BACKLIGHT_PWM_FREQUENCY
#  define CONFIG_LVGL_APP_BACKLIGHT_PWM_FREQUENCY 1000
#endif

#ifndef CONFIG_LVGL_APP_BACKLIGHT_PWM_CHANNEL
#  define CONFIG_LVGL_APP_BACKLIGHT_PWM_CHANNEL 1
#endif

#ifndef CONFIG_LVGL_APP_BACKLIGHT_DEFAULT_PERCENT
#  define CONFIG_LVGL_APP_BACKLIGHT_DEFAULT_PERCENT 72
#endif

#endif /* LVGL_APP_CONFIG_H */
