include $(APPDIR)/Make.defs

PROGNAME  += wifistart
PRIORITY  += 100
STACKSIZE += 8192
MAINSRC   += wifistart.c

PROGNAME  += wifistop
PRIORITY  += 100
STACKSIZE += 4096
MAINSRC   += wifistop.c

PROGNAME  += wifiscan
PRIORITY  += 100
STACKSIZE += 8192
MAINSRC   += wifiscan.c

PROGNAME  += wificonnect
PRIORITY  += 100
STACKSIZE += 8192
MAINSRC   += wificonnect.c

PROGNAME  += wifidisconnect
PRIORITY  += 100
STACKSIZE += 4096
MAINSRC   += wifidisconnect.c

PROGNAME  += wifistatus
PRIORITY  += 100
STACKSIZE += 4096
MAINSRC   += wifistatus.c

include $(APPDIR)/Application.mk
